version: '3'
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=post_db 

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    # ...

  redis:
    image: redis:latest
    restart: unless-stopped  

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
     container_name: flower
     build: .
     command: celery -A celery_worker flower --port=5555
     ports:
       - 5556:5555
     environment:
       - CELERY_BROKER_URL=${CELERY_BROKER_URL}
       - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
     depends_on:
       - app
       - redis
       - celery_worker